before_build:
  - cmd: git clone -q https://github.com/ChrisK91/SparklrSharp.git c:\projects\sparklrwp\SparklrSharp --depth 1
  - ps: $env:PLATFORM
  
shallow_clone: false # git tag doesn't work if it's true

artifacts:
  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\ARM\Debug\SparklrForWindowsPhone_Debug_ARM.xap
    name: Sparklr ARM Debug

  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\ARM\Release\SparklrForWindowsPhone_Release_ARM.xap
    name: Sparklr ARM Release

  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\x86\Debug\SparklrForWindowsPhone_Debug_x86.xap
    name: Sparklr x86 Debug

  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\x86\Release\SparklrForWindowsPhone_Release_x86.xap
    name: Sparklr x86 Release

platform:
  - ARM
  - x86

configuration:
  - Release
  #- Debug

test: off

build:
  project: SparklrForWindowsPhone\SparklrForWindowsPhone.sln
  verbosity: normal
  
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: ARM
      configuration: Debug
      
on_success:
  - cmd: git tag %PLATFORM%_%APPVEYOR_BUILD_VERSION%
  - cmd: git push https://6540826d8a3b35ee133e148a1b2000502fd90e07:@github.com/2spark/SparklrWP.git --tags
  - cmd: JSON=%(printf '{"tag_name": "%PLATFORM%_%APPVEYOR_BUILD_VERSION%","target_commitish": "GC","name": "2spark v%APPVEYOR_BUILD_VERSION% for %PLATFORM% devices","body": "Release of 2spark app v%PLATFORM%_%APPVEYOR_BUILD_VERSION%\n %APPVEYOR_REPO_COMMIT_MESSAGE%","draft": false,"prerelease": true}')
  - cmd: curl --data %JSON% https://api.github.com/repos/2spark/SparklrWP/releases?access_token=6540826d8a3b35ee133e148a1b2000502fd90e07



