before_build:
  - cmd: git clone -q https://github.com/ChrisK91/SparklrSharp.git c:\projects\sparklrwp\SparklrSharp --depth 1
  - ps: $env:PLATFORM
  
shallow_clone: false # git tag doesn't work if it's true

artifacts:
  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\ARM\Debug\SparklrForWindowsPhone_Debug_ARM.xap
    name: Sparklr ARM Debug

  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\ARM\Release\SparklrForWindowsPhone_Release_ARM.xap
    name: Sparklr ARM Release

  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\x86\Debug\SparklrForWindowsPhone_Debug_x86.xap
    name: Sparklr x86 Debug

  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\x86\Release\SparklrForWindowsPhone_Release_x86.xap
    name: Sparklr x86 Release

platform:
  - ARM
  - x86

configuration:
  - Release
  #- Debug

test: off

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


build:
  project: SparklrForWindowsPhone\SparklrForWindowsPhone.sln
  verbosity: normal
  
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: ARM
      configuration: Debug
      
on_success:
  - cmd: AppVeyorBuildReleases.bat

