before_build:
  - cmd: git clone -q https://github.com/ChrisK91/SparklrSharp.git c:\projects\sparklrwp\SparklrSharp

artifacts:
  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\ARM\Debug\SparklrForWindowsPhone_Debug_ARM.xap
    name: Sparklr ARM Debug

  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\ARM\Release\SparklrForWindowsPhone_Release_ARM.xap
    name: Sparklr ARM Release

  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\x86\Debug\SparklrForWindowsPhone_Debug_x86.xap
    name: Sparklr x86 Debug

  - path: SparklrForWindowsPhone\SparklrForWindowsPhone\Bin\x86\Release\SparklrForWindowsPhone_Release_x86.xap
    name: Sparklr x86 Release


platform:
  - x86
  - ARM

configuration:
  - Debug
  - Release

test: off

build:
  project: SparklrForWindowsPhone\SparklrForWindowsPhone.sln
  verbosity: normal
